name: build

on:
  create:
    tags:
      - v*
  push:
    branches:
      - master
  pull_request:

env:
  IMAGE_NAME: ghcr.io/paytmlabs/kubernetes-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Hadolint
        uses: hadolint/hadolint-action@v1.6.0

  build:
    needs: [lint]
    runs-on: ubuntu-latest
    permissions:
      packages: write

    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.12.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@v2.8.0
        with:
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Test container image
        run: >-
          docker run --rm
          --volume="${PWD}/test.sh:/test/test.sh:ro"
          "${IMAGE_NAME}:latest" /test/test.sh

      - name: Set container image tag
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: echo "IMAGE_TAG=${GITHUB_REF##refs/tags/v}" > "${GITHUB_ENV}"

      - name: Push container image
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: docker/build-push-action@v2.8.0
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
